// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test.proto

#ifndef PROTOBUF_Test_2eproto__INCLUDED
#define PROTOBUF_Test_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Test_2eproto();
void protobuf_AssignDesc_Test_2eproto();
void protobuf_ShutdownFile_Test_2eproto();

class TestRequest;
class TestResponse;

// ===================================================================

class TestRequest : public ::google::protobuf::Message {
 public:
  TestRequest();
  virtual ~TestRequest();
  
  TestRequest(const TestRequest& from);
  
  inline TestRequest& operator=(const TestRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const TestRequest& default_instance();
  
  void Swap(TestRequest* other);
  
  // implements Message ----------------------------------------------
  
  TestRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TestRequest& from);
  void MergeFrom(const TestRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 num = 1;
  inline bool has_num() const;
  inline void clear_num();
  static const int kNumFieldNumber = 1;
  inline ::google::protobuf::int32 num() const;
  inline void set_num(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:TestRequest)
 private:
  inline void set_has_num();
  inline void clear_has_num();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 num_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_Test_2eproto();
  friend void protobuf_AssignDesc_Test_2eproto();
  friend void protobuf_ShutdownFile_Test_2eproto();
  
  void InitAsDefaultInstance();
  static TestRequest* default_instance_;
};
// -------------------------------------------------------------------

class TestResponse : public ::google::protobuf::Message {
 public:
  TestResponse();
  virtual ~TestResponse();
  
  TestResponse(const TestResponse& from);
  
  inline TestResponse& operator=(const TestResponse& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const TestResponse& default_instance();
  
  void Swap(TestResponse* other);
  
  // implements Message ----------------------------------------------
  
  TestResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TestResponse& from);
  void MergeFrom(const TestResponse& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 num = 1;
  inline bool has_num() const;
  inline void clear_num();
  static const int kNumFieldNumber = 1;
  inline ::google::protobuf::int32 num() const;
  inline void set_num(::google::protobuf::int32 value);
  
  // required int32 returnVal = 2;
  inline bool has_returnval() const;
  inline void clear_returnval();
  static const int kReturnValFieldNumber = 2;
  inline ::google::protobuf::int32 returnval() const;
  inline void set_returnval(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:TestResponse)
 private:
  inline void set_has_num();
  inline void clear_has_num();
  inline void set_has_returnval();
  inline void clear_has_returnval();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 num_;
  ::google::protobuf::int32 returnval_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_Test_2eproto();
  friend void protobuf_AssignDesc_Test_2eproto();
  friend void protobuf_ShutdownFile_Test_2eproto();
  
  void InitAsDefaultInstance();
  static TestResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// TestRequest

// required int32 num = 1;
inline bool TestRequest::has_num() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TestRequest::set_has_num() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TestRequest::clear_has_num() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TestRequest::clear_num() {
  num_ = 0;
  clear_has_num();
}
inline ::google::protobuf::int32 TestRequest::num() const {
  return num_;
}
inline void TestRequest::set_num(::google::protobuf::int32 value) {
  set_has_num();
  num_ = value;
}

// -------------------------------------------------------------------

// TestResponse

// required int32 num = 1;
inline bool TestResponse::has_num() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TestResponse::set_has_num() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TestResponse::clear_has_num() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TestResponse::clear_num() {
  num_ = 0;
  clear_has_num();
}
inline ::google::protobuf::int32 TestResponse::num() const {
  return num_;
}
inline void TestResponse::set_num(::google::protobuf::int32 value) {
  set_has_num();
  num_ = value;
}

// required int32 returnVal = 2;
inline bool TestResponse::has_returnval() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TestResponse::set_has_returnval() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TestResponse::clear_has_returnval() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TestResponse::clear_returnval() {
  returnval_ = 0;
  clear_has_returnval();
}
inline ::google::protobuf::int32 TestResponse::returnval() const {
  return returnval_;
}
inline void TestResponse::set_returnval(::google::protobuf::int32 value) {
  set_has_returnval();
  returnval_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Test_2eproto__INCLUDED
